### ISSUE TITLE
TODO-Liste sn01

### ISSUE THREAD

**Issue by lemoer** [freifunkh/ansible#82]
IPv4
-----
- [x] Schema für die IPv4-Addressen ausdenken.
- [x] IP-Addressen entsprechend diesem neuen Schema in Networkd einbauen. (ggf. auch auf dem pve nachjustieren)
- [x] Die 45.12.203.12 als Exit-IP-Nutzen. (https://github.com/freifunkh/ansible/commit/f21bb56748d35204ecb698d5d7a3301568ed5c5c)
- [x] Die 45.12.203.11 im DNS eintragen, sodass die fastd-Clients sich hierhin verbinden.
- [x] Gre / GreTap auf sn01 neu generieren, sodass `Local=45.12.203.11` in /etc/systemd/network/19-gt-\*.netdev und /etc/systemd/network/19-gre-*.netdev .
- [x] Die Gre-Tunnel und GreTap-Tunnel auf allen anderen Supernodes neu generieren lassen, sodass die 45.12.203.11 als Ziel genutzt wird.

IPv6
------
- [x] Schema für die IPv6-Addressen ausdenken.
- [x] IP-Addressen entsprechend diesem neuen Schema in Networkd einbauen. (ggf. auch auf dem pve nachjustieren)
- [x] Mal eine statische IP auf dem Client geben, um das Routing zu prüfen.
- [x] Radvd-Config muss auf sn01 angepasst werden.
- [x] Die IPv6-Addresse im DNS eintragen, sodass die fastd-Clients sich hierhin verbinden.
- [ ] OPTIONAL: Sollten alle anderen Supernodes eine statische IP-Addresse aus dem Netz bekommen, sodass sie das Netz direkt über das batman routen können? Alternativ würden sie es durch's Internet routen.

**Comment by AiyionPrime** [comment]
Ich bin fertig. Die v4- und v6-Adressen sind erfolgreich umgezogen worden.
Alle Supernodes sind auf master Stand. Alle gretap devices sind erzeugt worden.
Auch ns1 wurde erfolgreich ausgerollt, als nebeneffekt wurde die Änderungen von Sush (gestern) veröffentlicht.

Somit bleibt lediglich die Frage nach den anderen Supernodes, die eigentlich keine Frage mehr zu sn01 ist;
aber weil sie hier schon steht, können wir sie auch noch eben klären.

@lemoer @ctandi @1977er

**Comment by AiyionPrime** [comment]
@lemoer ist dagegen, Pakete zwischen supernodes könnten unter Umständen nicht mehr zugestellt werden, wenn via gre geroutet würde, weil das Interface dem Inernet vorgezogen würde.

Keiner von uns will das gerne haben, closed.
